apiVersion: skaffold/v2beta24
kind: Config
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: ticketing-dev-329902
  artifacts:
  - image: us.gcr.io/ticketing-dev-329902/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
